# Generated by Django 4.0 on 2023-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=200, unique=True, verbose_name='UUID')),
                ('source', models.CharField(choices=[('WEB_PORTAL', 'WEB_PORTAL'), ('MOBILE_APP', 'MOBILE_APP'), ('BACKEND', 'BACKEND')], default='BACKEND', max_length=50, verbose_name='Request Source')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Info',
                'verbose_name_plural': 'User Info',
            },
        ),
    ]
